isomerpages/ogp

_careers/2-software-engineer.md

Copyedit, have two buttons for full-time and intern hires

---

_layouts/opengovsg-landing-page.html

Fix opendoc link on landing page

---

_hackathon/1-hackathon-2021.md

Updating Lookback and Common.gov.sg

Updating Hackathon 2021 Project Names

---

_careers/1-product-manager.md
_careers/2-software-engineer.md
_careers/3-ux-designer.md
_careers/4-internships.md
_hackathon/anything-mapper.md
_hackathon/checkfirst.md
_hackathon/chopchopdoc.md
_hackathon/common.md
_hackathon/dash.md
_hackathon/diffindo.md
_hackathon/govsearch.md
_hackathon/handsy.md
_hackathon/helpgov.md
_hackathon/lookback.md
_hackathon/payments.md
_hackathon/personalised-forms.md
_hackathon/queue.md
_hackathon/transparency.md
_hackathon/typesafe.md
misc/custom.scss

- Change in text for job roles
- Hotfix dropdown menus
- Change slides width for hackathon projects to 100%

Push changes to master

---

_careers/4-internships.md

Highlight what internships are available, and minimum duration/period of each

Adjust wording on intern page

---

_includes/people-of-OGP.html

Request from Shannen to sort the Team page.
Lifted from this [Jekyll tutorial](https://templates.supply/sort-jekyll-collection-by-reverse-order-and-limit-results/)
FYI @cakesoccer

feature(team): Sort people by name

---

_hack-for-public-good/Hack for Public Good 2022/UnboringSG.md

Hey @cakesoccer @shannenho thanks again for having me as part of HfPG at the beginning of this year. I was wondering if you'd might consider adding the team members to each hackathon project, maybe in a list like this? Wdyt?

feat: add team members.

---

_layouts/opengovsg-landing-page.html

See commit log for specific changes

Adjust font size for mobile screens

---

_careers/product-design.md

Changed previous video with Fiza to the latest video featuring Jingyi.

Update product design page video

---

_data/ogp-products.yml
_includes/ogp-products.html
_products/Our Products.md
serve.sh

feat: products new look

---

_layouts/opengovsg-landing-page.html
_products/Our Products.md
_redirects

Use `/products` vs `/products/overview`

feat: shorten products overview page link

---

_data/products.yml
_includes/ogp-products.html

Adding a new category `Government Digital Infrastructure` which contains 2 products:
* datagovsg
* sgid

feat: update product categorization

---

_about-us/design/shanty.md
_about-us/ops/shazli.md
_about-us/ops/suhaila.md
_about-us/pm/cheryl.md
_about-us/pm/kenneth.md
_about-us/pm/lennard.md
_config.yml
_data/products.yml
_includes/ogp-products.html
_layouts/opengovsg-landing-page.html
_products/Our Products.md
_redirects
netlify.toml

This is how a PR from `staging` to `master`
@ogpjolo

feat: push staff page changes to production

---

_about-us/transformation/hygin.md

chore: more updates for q3 2023

---

_data/products.yml
pages/contact-us.md

Updating Contact Us page with email subscription form. Started a new section for email subscription.

Updating Contact Us page with email subscription form

---

_about-us/corporate/nicole.md
_our-products/Care360.md

fixed typo from "managemenet" -> "management"

fix: typo in Care360 Product page

---

_our-products/Pair.md

updated pair description and team

updated pair description and team

---

_about-us/design/shanty.md

Deploying #199 to prod
cc @amitogp

Put FormSG under 2 product categories

---

_data/products.yml

chore: update products page

---

_redirects
pages/Life@OGP.md

- Added CareerSG, Briskwalker and SBS
- Updated Scamshield logo
- Updated KampungSpirit status
- added redirect for /international

Release 19 Sep
